---
- name: Post Install components
  hosts: masters
  become: true
  pre_tasks:
    - name: Include sanity check
      ansible.builtin.include_tasks: sanity_check.yaml
      tags: [always]
  roles:
    - role: kubectl
      tags: [kubectl]

    - role: helm
      tags: [helm]

    - role: kube_network
      tags: [kube_network]

    - name: Approve bootstrap certificate requests
      role: kube_csr
      tags: [kube_csr]
